version: '2'

volumes:
  wildfly_data:
  oracle_data:
  oracle-backup:

services:
  wildfly:
    container_name: wildfly
    image: quay.io/wildfly/wildfly
    ports:
      - '8080:8080'
      - '9990:9990'
    volumes:
      - 'wildfly_data:/opt/jboss/wildfly/'
    environment:
      - WILDFLY_PASSWORD=password
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
    ports:
      - 5500:5500
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup