version: '2'

volumes:
  wildfly_data:

services:
  wildfly:
    container_name: wildfly
    image: quay.io/wildfly/wildfly
    ports:
      - '8080:8080'
      - '9990:9990'
    volumes:
      - 'wildfly_data:/opt/jboss/wildfly/'
    environment:
      - WILDFLY_PASSWORD=password